spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/osu_iomo
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true

